/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "combo.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statuscmd.h"
#include "bar_tabgroups.h"
#include "bar_tags.h"
#include "bar_tagpreview.h"
#include "bar_taggrid.h"
#include "bar_wintitle.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "alttab.h"
#include "keymodes.h"
#include "moveresize.h"
#include "movestack.h"
#include "nametag.h"
#include "pertag.h"
#include "swallow.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
#include "xrdb.h"
/* Layouts */
#include "layout_flextile-deluxe.h"
#include "layout_gapplessgrid.h"
#include "layout_grid.h"
#include "layout_monocle.h"
#include "layout_tile.h"

